### ISSUE TITLE
heroku error

### ISSUE THREAD

**Issue by jcrush2** [oldkiller/karmator_bot#4]
Привет, не подскажешь, почему у меня не получается завести бота?

`2020-10-30T13:08:43.516275+00:00 heroku[router]: at=info method=POST path="/bot" host=khabarabot.herokuapp.com request_id=0e24bfe4-29bf-45a3-8fb6-c8b2bf068946 fwd="91.108.6.103" dyno=web.1 connect=1ms service=5ms status=200 bytes=154 protocol=https
2020-10-30T13:08:43.512000+00:00 app[web.1]: _internal.py [Line:113]# INFO     [2020-10-30 13:08:43,511] 10.10.68.189 - - [30/Oct/2020 13:08:43] "POST /bot HTTP/1.1" 200 -
2020-10-30T13:08:43.514409+00:00 app[web.1]: 2020-10-30 13:08:43,514 (util.py:75 WorkerThread1) ERROR - TeleBot: "InternalError occurred, args=('current transaction is aborted, commands ignored until end of transaction block\n',)
2020-10-30T13:08:43.514410+00:00 app[web.1]: Traceback (most recent call last):
2020-10-30T13:08:43.514411+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/peewee.py", line 3099, in execute_sql
`

**Comment by jcrush2** [comment]
т.е. на команду /help бот реагирует, а вот карму не считает

**Comment by oldkiller** [comment]
Предполагаю, что возникла ошибка базы. Хм. 
А база и таблицы существуют?
Если что, адрес для подключения можно взять из системной переменной Heroku "DATABASE_URL".

**Comment by jcrush2** [comment]
> Предполагаю, что возникла ошибка базы. Хм.
> А база и таблицы существуют?
> Если что, адрес для подключения можно взять из системной переменной Heroku "DATABASE_URL".

спасибо за ответ, базу я создал, но похоже она пустая

UTILIZATION
2 of 20
CONNECTIONS
0 of 10,000
ROWS IN COMPLIANCE
7.9 MB
DATA SIZE
0
TABLES
![Screenshot from 2020-10-30 23-49-16](https://user-images.githubusercontent.com/32280851/97712719-8e8a8e00-1b0a-11eb-9d02-3eb77ab2ec7b.png)

**Comment by oldkiller** [comment]
Если что, почитайте по поводу создания таблиц в peewee:
http://docs.peewee-orm.com/en/latest/peewee/quickstart.html
```
db = SqliteDatabase('people.db')

class Pet(Model):
    owner = ForeignKeyField(Person, backref='pets')
    name = CharField()
    animal_type = CharField()

db.create_tables([Pet])  # создание таблицы Pet
```
```
db.create_table([Limitation, KarmaUser])
```
Хм. Насколько я помню, у бота есть маленький нюанс. Который у меня не доходили руки решить:
Он довольно своеобразно ведет подсчет ограничения на изменение кармы.
Каждый раз, когда меняется карма, идет запись в таблицу Limitation. А на команду SELECT привязан триггер БД (код можно найти в файле "schema.sql"), который удаляет записи, которые старше чем некий промежуток времени. Если такого триггера нет, то со временем база забьется старыми записями.
Так что тут есть 2 пути. Или добавлять триггер в БД (что вроде бы нельзя сделать средствами peewee, и нужно идти через консоль), либо добавлять примерно такой код в функцию "is_karma_abuse" перед командой return:
```
limits = Limitation.delete().where(Limitation.timer > hours_ago_12)
limits.execute()
```
К сожалению, я сейчас не могу поправить это сам. Но этот код должен работать.

**Comment by jcrush2** [comment]
> Если что, почитайте по поводу создания таблиц в peewee:
> http://docs.peewee-orm.com/en/latest/peewee/quickstart.html
> 
> ```
> db = SqliteDatabase('people.db')
> 
> class Pet(Model):
>     owner = ForeignKeyField(Person, backref='pets')
>     name = CharField()
>     animal_type = CharField()
> 
> db.create_tables([Pet])  # создание таблицы Pet
> ```
> 
> ```
> db.create_table([Limitation, KarmaUser])
> ```
> 
> Хм. Насколько я помню, у бота есть маленький нюанс. Который у меня не доходили руки решить:
> Он довольно своеобразно ведет подсчет ограничения на изменение кармы.
> Каждый раз, когда меняется карма, идет запись в таблицу Limitation. А на команду SELECT привязан триггер БД (код можно найти в файле "schema.sql"), который удаляет записи, которые старше чем некий промежуток времени. Если такого триггера нет, то со временем база забьется старыми записями.
> Так что тут есть 2 пути. Или добавлять триггер в БД (что вроде бы нельзя сделать средствами peewee, и нужно идти через консоль), либо добавлять примерно такой код в функцию "is_karma_abuse" перед командой return:
> 
> ```
> limits = Limitation.delete().where(Limitation.timer > hours_ago_12)
> limits.execute()
> ```
> 
> К сожалению, я сейчас не могу поправить это сам. Но этот код должен работать.

как я понял надо создать таблицы и колонки вручную?
застрял на этом:
`khabarabot::DATABASE=> CREATE TABLE karma_user (userid integer NOT NULL, userid integer NOT NULL, karma integer NOT NULL, user_name varchar(100) NOT NULL, user_nick varchar(50) NOT NULL, is_banned BOOL DEFAULT 'f');
ERROR:  column "userid" specified more than once
khabarabot::DATABASE=> 

или это не оно?`

**Comment by oldkiller** [comment]
1. У Вас 2-жды объявлена колонка userid, и ни разу chatid
2. Можно и так создать

**Comment by jcrush2** [comment]
Создал 2 таблицы:
`CREATE TABLE karma_user (userid int NOT NULL,chatid int NOT NULL,karma int NULL DEFAULT 0,user_name char(100) NULL,user_nick char(50) NULL,is_banned bool,PRIMARY KEY (userid,chatid))
CREATE TABLE limitation (userid int not null,chatid int not null,timer TIMESTAMP not NULL)`

но все равно не работает

`020-10-31T00:49:44.107628+00:00 heroku[router]: at=info method=POST path="/bot" host=khabarabot.herokuapp.com request_id=c386a1f0-a29e-47ce-b898-63a54b1f331a fwd="91.108.6.103" dyno=web.1 connect=1ms service=4ms status=200 bytes=154 protocol=https
2020-10-31T00:49:44.102991+00:00 app[web.1]: _internal.py [Line:113]# INFO     [2020-10-31 00:49:44,102] 10.11.191.99 - - [31/Oct/2020 00:49:44] "POST /bot HTTP/1.1" 200 -
2020-10-31T00:49:44.339903+00:00 app[web.1]: 2020-10-31 00:49:44,339 (util.py:75 WorkerThread1) ERROR - TeleBot: "DataError occurred, args=('integer out of range\n',)
2020-10-31T00:49:44.339905+00:00 app[web.1]: Traceback (most recent call last):
2020-10-31T00:49:44.339908+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/peewee.py", line 3099, in execute_sql
2020-10-31T00:49:44.339909+00:00 app[web.1]: cursor.execute(sql, params or ())
2020-10-31T00:49:44.339910+00:00 app[web.1]: psycopg2.errors.NumericValueOutOfRange: integer out of range
2020-10-31T00:49:44.339911+00:00 app[web.1]: 
2020-10-31T00:49:44.339911+00:00 app[web.1]: 
2020-10-31T00:49:44.339912+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-10-31T00:49:44.339912+00:00 app[web.1]: 
2020-10-31T00:49:44.339913+00:00 app[web.1]: Traceback (most recent call last):
2020-10-31T00:49:44.339913+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/telebot/util.py", line 69, in run
2020-10-31T00:49:44.339914+00:00 app[web.1]: task(*args, **kwargs)
2020-10-31T00:49:44.339915+00:00 app[web.1]: File "karmator.py", line 452, in changing_karma_text
2020-10-31T00:49:44.339915+00:00 app[web.1]: reputation(msg, msg.text)
2020-10-31T00:49:44.339916+00:00 app[web.1]: File "karmator.py", line 423, in reputation
2020-10-31T00:49:44.339916+00:00 app[web.1]: chatid=msg.chat.id)
`

**Comment by jcrush2** [comment]
может на бесплатном тарифе оно не работает?

`2020-10-31T01:01:41.689925+00:00 app[web.1]: 2020-10-31 01:01:41,689 (util.py:75 WorkerThread2) ERROR - TeleBot: "InternalError occurred, args=('current transaction is aborted, commands ignored until end of transaction block\n',)
`

**Comment by jcrush2** [comment]
я заменил запросы с INT на bigint и ошибки пропали, спасибо за бота, давно искал что то простое для кармы, буду дальше ковырять, не забрасывай, кроме кармы можно рейтинги дописать..

`CREATE TABLE karma_user (userid bigint NOT NULL,chatid bigint NOT NULL,karma bigint NULL DEFAULT 0,user_name char(100) NULL,user_nick char(50) NULL,is_banned bool,PRIMARY KEY (userid,chatid));

-- create table for limiting karm
CREATE TABLE limitation (userid bigint not null,chatid bigint not null,timer TIMESTAMP not NULL);`
